name: mensajeria_app
description: "App móvil del sistema de mensajería corporativa - Examen UPB"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # ──── Firebase ────
  firebase_core: ^4.8.0
  firebase_messaging: ^16.2.1

  # ──── State management ────
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

  # ──── Navegación ────
  go_router: ^17.2.3

  # ──── Networking ────
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # ──── Storage ────
  flutter_secure_storage: ^10.1.0
  shared_preferences: ^2.3.2

  # ──── Modelos / serialización ────
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # ──── UI / imágenes ────
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  google_fonts: ^8.1.0
  lucide_icons: ^0.257.0
  shimmer: ^3.0.0

  # ──── Animaciones ────
  animations: ^2.0.11

  # ──── Login social (Adicional 2) ────
  flutter_facebook_auth: ^7.1.1

  # ──── Utilidades ────
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Linting
  custom_lint: ^0.8.1
  riverpod_lint: ^3.1.0

  # Code generation
  build_runner: ^2.5.4
  riverpod_generator: ^4.0.0+1
  freezed: ^3.0.6
  json_serializable: ^6.9.0
