// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDILRY8Ir97a_kGzIGZc73RzSP0S4HLRsI',
    appId: '1:109948491316:web:3bd6c4ce78b31623f5dc61',
    messagingSenderId: '109948491316',
    projectId: 'mensajeria-corporativa',
    authDomain: 'mensajeria-corporativa.firebaseapp.com',
    storageBucket: 'mensajeria-corporativa.firebasestorage.app',
    measurementId: 'G-5LTR9FD40L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOjejl0dEb7suC7I_Tm_acknlWzVjBH1A',
    appId: '1:109948491316:android:7ce8767c9a9d3205f5dc61',
    messagingSenderId: '109948491316',
    projectId: 'mensajeria-corporativa',
    storageBucket: 'mensajeria-corporativa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSG2wWjHUQVOCk-mQl28vRjCvknroHGJY',
    appId: '1:109948491316:ios:56e25f224dd5330ff5dc61',
    messagingSenderId: '109948491316',
    projectId: 'mensajeria-corporativa',
    storageBucket: 'mensajeria-corporativa.firebasestorage.app',
    iosBundleId: 'com.upb.mensajeria.mensajeriaApp',
  );
}
